
logsBucket: cloudbuild-logs-479403 

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', 'dags/', 'gs://us-central1-earthquake-comp-d4045531/dags']
  id: 'Deploy DAGs'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', 'dags/scripts/', 'gs://us-central1-earthquake-comp-d4045531/dags/scripts']
  id: 'Deploy Python Scripts'